var mongoose = require("mongoose");
var Schema = mongoose.Schema;

//var employee = require('../models/employeeModel');

var customerSchema = new Schema({
    company_name        : {type: String},
    name                : {type: String},
    email_id            : {type: String},
    mobile_no           : {type: String},
    landline            : {type: String},
    dob                 : {type: Date},
    address             : {type: String},
    state               : {type: String},
    city                : {type: String},
    flat_no             : {type: String},
    area                : {type: String},
    subarea             : {type: String},
    wings               : {type: String},
    gender              : {type: String},
    floor               : {type: String},
    building            : {type: String},
    landmark            : {type: String},
    pin_code            : {type: String},
    country             : {type: String},
    society             : {type: String},
    lane                : {type: String},
    distributor_ref_id  : {type: String},
    proof_of_documents   : [{
        doc_url          : {type: String},
        type             : {type: String},
        id_proof_name    : {type: String},
        image_name       : {type: String},
        createdAt       : {type: Date, default:Date.now},
    }],
    profile_url          : {type: String},
    created_by           : {type: String},
    can_id               : {type: String},
    stb_no               : {type: String},
    mso                  : {type: String},
    isp                  : {type: String},
    tax                  : {type: String},
    remarks              : {type: String},
    //emp_ref_id           : {type: Schema.ObjectId, ref:"employee"},
    staff_email          : {type: String},
    staff_name           : {type: String},
    complaint_forward_to : {type: String},
    assign_to            : {type: String},
    account_id           : {type: String},
    account_no           : {type: String},
    remark               : {type: String},
    checque_bank_name    : {type: String},
    checque_date         : {type: Date},
    checque_no           : {type: String},
    bill_no              : {type: String},
    collected_by         : {type: String},
    trans_type           : {type: String},
    installation_amount  : {type: Number},
    payment_type         : {type: String},
    tax_amount           : {type: Number},
    is_active            : {type: Boolean, default: false},
    is_deleted           : {type: Boolean, default: false},
    // created_at           : {type: Date, default: Date.now}
});

module.exports = mongoose.model("customers",customerSchema,"customers");